name: Build and Deploy DocC

on:
  push:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "docc-pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build DocC
    runs-on: macos-13
    steps:
      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Show Xcode version
        run: |
          xcodebuild -version
          swift --version

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build DocC Archive & Static Site
        run: |
          set -euo pipefail

          SCHEME="SwiftHelpers"
          OUTPUT_DIR=".docs"
          DERIVED_DATA=".docc-build"
          HOSTING_BASE_PATH="SwiftHelpers"

          echo "🛠️ Building documentation for scheme: $SCHEME"
          xcodebuild docbuild \
            -scheme "$SCHEME" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath "$DERIVED_DATA"

          ARCHIVE_PATH=$(find "$DERIVED_DATA" -name "*.doccarchive" | head -n 1)

          echo "📁 Found doccarchive at: $ARCHIVE_PATH"

          echo "🌐 Generating static site..."
          docc process-archive \
            transform-for-static-hosting "$ARCHIVE_PATH" \
            --output-path "$OUTPUT_DIR" \
            --hosting-base-path "$HOSTING_BASE_PATH"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static site to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: .docs

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v2
