name: Build and Deploy DocC

on:
  push:
    branches: [ '*' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build DocC
    runs-on: macos-latest
    steps:
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build DocC static site
        uses: kiarashvosough1999/build-docC-static-site@v1.0.3
        with:
          docC-generated-static-site-zipped-upload-name: docC_generated_site_zipped

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.docC-page_url }}
    steps:
      - name: Deploy DocC site
        id: deploy
        uses: kiarashvosough1999/docC-github-pages-deploy@v1.0.0
        with:
          docC-generated-static-site-uploaded-name: docC_generated_site_zipped
