# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-macos:
    name: macOS Tests
    runs-on: macos-15
    steps:
      - name: Select Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run macOS Tests
        run: swift test --enable-code-coverage
